server:
  port: 8111
  frontendRoot:
    eu: 'http://local.chaosarchives.org:8080'
    na: 'http://local.crystalarchives.org:8080'
    global: 'http://local.centralarchives.org:8080'
  newsRoot: 'http://localhost:8081'
  maxUploadSpacePerUserMiB: 500
  stewardWebhookPort: 8112
  stewardWebhookUrl: 'http://steward:8112'
  apis:
    rpp: true

db:
  type: 'mariadb'
  host: 'mariadb'
  port: 3306
  database: 'chaosarchives'
  username: 'mariadb'
  password: 'mariadb'
  synchronize: false
  logging: true

redis:
  host: 'redis'
  port: 6379

mail:
  host: 'smtp.example.com'
  port: 25
  secure: true
  username: 'user'
  password: 'password'
  from:
    eu: 'Chaos Archives <chaosarchives@localhost>'
    na: 'Crystal Archives <crystalarchives@localhost>'
    global: 'Central Archives <centralarchives@localhost>'

auth:
  jwtSecret: 'secret'
  jwtExpiry: '30d'
  scopedJwtExpiry: '365d'

s3:
  endpoint: 'http://localhost:9000'
  region: ''
  bucketName: 'chaosarchives'
  publicRootUrl: 'http://localhost:9000/chaosarchives'
  accessKeyId: 'minioadmin'
  secretAccessKey: 'minioadmin'

discord:
  botToken: 'INSERT_TOKEN_HERE'
  serverId: 'INSERT_ID_HERE'
  announcementChannels:
    Chaos: 'INSERT_ID_HERE'
    Light: 'INSERT_ID_HERE'
  noticeboardChannel: 'INSERT_ID_HERE'
