<template>
  <section class="two-factor-auth">
    <h3>Two-Factor Authentication</h3>
    <p>
      Two-factor authentication improves the security of your account by requiring a one-time password (OTP) every time
      you log in, in addition to your regular password. This makes it harder for hackers to steal your account.
    </p>
    <section v-if="user2FAStatus.state === User2FAState.DISABLED">
      <q-btn color="primary" label="Set up two-factor authentication" @click="setup2FA" />
    </section>
    <section v-if="user2FAStatus.state === User2FAState.REQUESTED">
      To set up two-factor authentication, follow these steps.

      <ol>
        <li>
          <p>Scan the QR code below with the authenticator app of your choice.</p>
          <p>
            You can use apps like Google Authenticator or
            <a href="https://getaegis.app/" target="_blank"
              >Aegis <q-icon class="external-link-icon" name="launch"
            /></a>
            on a mobile phone, or the
            <a href="https://authenticator.cc/" target="_blank"
              >Authenticator.cc <q-icon class="external-link-icon" name="launch"
            /></a>
            browser extension, or any other compatible app.
          </p>
          <p>
            <img v-if="user2FAStatus.qrDataUrl" :src="user2FAStatus.qrDataUrl" />
          </p>
        </li>
        <li>
          <p>
            Input your current password and a one-time password generated by your authenticator app (six digits), then
            press Finish Setup.
          </p>
          <q-input
            ref="currentPasswordField"
            v-model="currentPassword"
            label="Current password"
            auto
            type="password"
            :rules="[
              $rules.required('This field is required.'),
              $rules.minLength(
                SharedConstants.PASSWORD_MIN_LENGTH,
                `Password must be at least ${SharedConstants.PASSWORD_MIN_LENGTH} characters long.`
              ),
            ]"
            @focus="onCurrentPasswordFocus"
          >
            <template v-slot:prepend>
              <q-icon name="password" />
            </template>
          </q-input>
          <q-input
            v-model="otp"
            label="One-time password"
            :rules="[
              $rules.required('This field is required.'),
              (val) => SharedConstants.OTP_REGEX.test(val) || 'Invalid one-time password',
            ]"
          >
            <template v-slot:prepend>
              <q-icon name="pin" />
            </template>
          </q-input>
        </li>
      </ol>
      <section class="button-bar">
        <q-btn color="secondary" label="Cancel" @click="cancelSetup" />&nbsp;
        <q-btn color="primary" label="Finish setup" :disabled="!isFinishSetupValid" @click="finishSetup" />
      </section>
    </section>
    <section v-else-if="user2FAStatus.state === User2FAState.ENABLED">
      <p>Two-factor authentication is currently <strong>enabled</strong> on your account.</p>
      <p>
        <q-btn color="secondary" label="Get new backup code" @click="getBackupCode" />
      </p>
      <q-btn color="negative" label="Remove two-factor authentication" @click="remove2FA" />
    </section>
    <q-inner-loading :showing="loading" />
  </section>
</template>

<script lang="ts">
import SharedConstants from '@app/shared/SharedConstants';
import { User2FAConfirmResponseDto } from '@app/shared/dto/user/2fa/user-2fa-confirm-response.dto';
import { User2FAStatusDto } from '@app/shared/dto/user/2fa/user-2fa-status.dto';
import { User2FAState } from '@app/shared/enums/user-2fa-state.dto';
import { QInput } from 'quasar';
import { notifyError } from 'src/common/notify';
import { Options, Vue } from 'vue-class-component';

@Options({
  name: 'TwoFactorAuth',
})
export default class TwoFactorAuth extends Vue {
  readonly User2FAState = User2FAState;
  readonly SharedConstants = SharedConstants;

  user2FAStatus: User2FAStatusDto = {
    state: User2FAState.DISABLED,
    qrDataUrl: null,
  };
  currentPassword = ' ';
  otp = '';

  loading = false;

  async created() {
    this.user2FAStatus = await this.$api.user2fa.getStatus();
  }

  get isFinishSetupValid() {
    return (
      this.currentPassword.trim() != '' &&
      this.currentPassword.length >= SharedConstants.PASSWORD_MIN_LENGTH &&
      SharedConstants.OTP_REGEX.test(this.otp)
    );
  }

  onCurrentPasswordFocus() {
    (this.$refs.currentPasswordField as QInput).select();
  }

  async setup2FA() {
    this.loading = true;

    try {
      this.user2FAStatus = await this.$api.user2fa.request();
      this.currentPassword = ' ';
      this.otp = '';
    } catch (e) {
      notifyError(e);
    } finally {
      this.loading = false;
    }
  }

  async cancelSetup() {
    this.loading = true;

    try {
      this.user2FAStatus = await this.$api.user2fa.cancel();
    } catch (e) {
      notifyError(e);
    } finally {
      this.loading = false;
    }
  }

  async finishSetup() {
    this.loading = true;

    try {
      const backupCodeResult = await this.$api.user2fa.confirm({
        currentPassword: this.currentPassword,
        otp: this.otp,
      });

      const BackupCodeDialog = (await import('components/account/BackupCodeDialog.vue')).default;

      this.$q.dialog({
        component: BackupCodeDialog,
        componentProps: {
          finishSetup: true,
          backupCode: backupCodeResult.backupCode,
        },
      });
    } catch (e) {
      notifyError(e);
    } finally {
      this.loading = false;
    }
  }

  async getBackupCode() {
    const GetBackupCodeDialog = (await import('components/account/GetBackupCodeDialog.vue')).default;

    this.$q
      .dialog({
        component: GetBackupCodeDialog,
      })
      .onOk(async (backupCodeResult: User2FAConfirmResponseDto) => {
        const BackupCodeDialog = (await import('components/account/BackupCodeDialog.vue')).default;

        this.$q.dialog({
          component: BackupCodeDialog,
          componentProps: {
            finishSetup: false,
            backupCode: backupCodeResult.backupCode,
          },
        });
      });
  }

  async remove2FA() {
    const ConfirmRemove2FADialog = (await import('components/account/ConfirmRemove2FADialog.vue')).default;

    this.$q
      .dialog({
        component: ConfirmRemove2FADialog,
      })
      .onOk((new2FAStatus: User2FAStatusDto) => {
        this.user2FAStatus = new2FAStatus;
      });
  }
}
</script>

<style lang="scss">
.two-factor-auth {
  max-width: 500px;
}
</style>
