name: Server Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Chaos Archives Docker image
      run: cd server && docker build . --file Dockerfile --tag chaosarchives:$(date +%s)
